app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    
    path('',include(('bases.urls', 'bases'), namespace='bases')),
    path('inv/',include(('inv.urls','inv'), namespace='inv')),
    path('vnt/',include(('vnt.urls','vnt'), namespace='vnt')),
    path('fac/',include(('fac.urls','fac'), namespace='fac')),
    path('apiRest/', include(('apiRest.urls', 'apiRest'), namespace='apiRest')),

    path('admin/', admin.site.urls),
]

inv/urls.py
from django.urls import path

from .views import CategoriaView, CategoriaNew, CategoriaEdit, CategoriaDelete,\
        SubCategoriaView, SubCategoriaNew, SubCategoriaEdit, SubCategoriaDelete,\
        ProductoView, ProductoNew, ProductoEdit,producto_inactivar, BitacoraView,\
        BitacoraNew, BitacoraEdit, BitacoraDelete, ProductoDelete

urlpatterns = [
    path('categorias/', CategoriaView.as_view(), name='categoria_list'),
    path('categorias/new', CategoriaNew.as_view(), name='categoria_new'),
    path('categorias/edit/<int:pk>', CategoriaEdit.as_view(), name='categoria_edit'),
    path('categorias/delete/<int:pk>', CategoriaDelete.as_view(), name='categoria_delete'),

    path('subcategorias/', SubCategoriaView.as_view(), name='subcategoria_list'),
    path('subcategorias/new', SubCategoriaNew.as_view(), name='subcategoria_new'),
    path('subcategorias/edit/<int:pk>', SubCategoriaEdit.as_view(), name='subcategoria_edit'),
    path('subcategorias/delete/<int:pk>', SubCategoriaDelete.as_view(), name='subcategoria_delete'),

    path('producto/', ProductoView.as_view(), name='producto_list'),
    path('producto/new', ProductoNew.as_view(), name='producto_new'),
    path('producto/edit/<int:pk>', ProductoEdit.as_view(), name='producto_edit'),
    path('producto/delete/<int:pk>', ProductoDelete.as_view(), name='producto_delete'),
    path('producto/inactiva/<int:id>', producto_inactivar, name='producto_inactivar'),

    path('bitacora/', BitacoraView.as_view(), name='bitacora_list'),
    path('bitacora/new', BitacoraNew.as_view(), name='bitacora_new'),
    path('bitacora/edit/<int:pk>', BitacoraEdit.as_view(), name='bitacora_edit'),
    path('bitacora/delete/<int:pk>', BitacoraDelete.as_view(), name='bitacora_delete'),
    
]

bases/models.py
from django.db import models

from django.contrib.auth.models import User
from django_userforeignkey.models.fields import UserForeignKey

class ClaseModelo(models.Model):
    estado = models.BooleanField(default=True)
    fc = models.DateTimeField(auto_now_add=True)
    fm = models.DateTimeField(auto_now=True)
    uc = models.ForeignKey(User, on_delete=models.CASCADE)
    um = models.IntegerField(blank=True,null=True)

    class Meta:
        abstract=True

class ClaseModeloVersDos(models.Model):
    estado = models.BooleanField(default=True)
    fc = models.DateTimeField(auto_now_add=True)
    fm = models.DateTimeField(auto_now=True)
    # uc = models.ForeignKey(User, on_delete=models.CASCADE)
    # um = models.IntegerField(blank=True,null=True)
    usuario_crea = UserForeignKey(auto_user_add=True,related_name='+')
    usuario_modifica = UserForeignKey(auto_user=True,related_name='+')

    class Meta:
        abstract=True

inv/models.py
from django.db import models

from bases.models import ClaseModelo

class Categoria(ClaseModelo):
    descripcion = models.CharField(
        max_length=100,
        help_text='Descripcion de la categoria',
        unique=True
    )

    def __str__(self):
        return '{}'.format(self.descripcion)

    def save(self):
        self.descripcion = self.descripcion.upper()
        super(Categoria, self).save()
    
    class Meta:
        verbose_name_plural= "Categorias"


class SubCategoria(ClaseModelo):
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    descripcion = models.CharField(
        max_length=100,
        help_text='Descripcion de la sub categoria'     
    )
    def __str__(self):
        return '{}:{}'.format(self.categoria.descripcion, self.descripcion)

    def save(self):
        self.descripcion = self.descripcion.upper()
        super(SubCategoria, self).save()

    class Meta:
        verbose_name_plural= "Sub Categorias"
        unique_together = ('categoria', 'descripcion')

class Producto(ClaseModelo):
    subCategoria = models.ForeignKey(SubCategoria, on_delete=models.CASCADE)
    codigo = models.CharField(
        max_length=20,
        unique=True
    )
    codigo_barra = models.CharField(max_length=50)
    descripcion = models.CharField(max_length=200)
    precio = models.FloatField(default=0)
    existencia = models.IntegerField(default=12)
    fecha_carga = models.DateField(null=True, blank=True)
    cantidad = models.IntegerField(default=0)
    comentario = models.CharField(max_length=200)


    def __str__(self):
        return '{}'.format(self.descripcion)

    def save(self):
        self.descripcion = self.descripcion.upper()
        super(Producto, self).save()
    
    class Meta:
        verbose_name_plural= "Productos"
        unique_together = ('codigo', 'codigo_barra')

class Bitacora(ClaseModelo):
    codigo = models.CharField(
        max_length=20,
        unique=True
    )
    subCategoria = models.ForeignKey(SubCategoria, on_delete=models.CASCADE)
    numero_documento = models.IntegerField(default=0)
    numero_viaje = models.IntegerField(default=0)
    fecha_recepcion = models.DateField(null=True, blank=True)
    hora_recepcion = models.DateField(null=True, blank=True)
    ubicacion = models.CharField(max_length=200)
    inicial = models.IntegerField(default=0)
    final = models.IntegerField(default=0)
    litros_recibidos = models.IntegerField(default=0)
    diferencia = models.IntegerField(default=0)
    tk = models.IntegerField(default=0)
    temperatura = models.IntegerField(default=0)
    api = models.FloatField(default=0)
    descripcion = models.CharField(max_length=200)
    

    def __str__(self):
        return '{}'.format(self.descripcion)

    def save(self):
        self.descripcion = self.descripcion.upper()
        super(Bitacora, self).save()

    class Meta:
        verbose_name_plural= "Bitacoras"
        

    

inv/forms.py
from django import forms

from .models import Categoria, SubCategoria, Producto, Bitacora


class CategoriaForm( forms.ModelForm):
    class Meta:
        model=Categoria
        fields = ['descripcion', 'estado']
        labels = {'descripcion':'Descripcion de la Categoria xx',
                    'estado':'Estado'}
        widget = {'descripcion': forms.TextInput}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control'
            })
    def clean(self):
        try:
            sc = Categoria.objects.get(
                descripcion=self.cleaned_data["descripcion"].upper()
            )

            if not self.instance.pk:
                print("Registro ya existe")
                raise forms.ValidationError("Registro Ya Existe")
            elif self.instance.pk!=sc.pk:
                print("Cambio no permitido")
                raise forms.ValidationError("Cambio No Permitido")
        except Categoria.DoesNotExist:
            pass
        return self.cleaned_data

class SubCategoriaForm( forms.ModelForm):
    categoria = forms.ModelChoiceField(
        queryset=Categoria.objects.filter(estado=True)
        .order_by('descripcion')
    )
    class Meta:
        model=SubCategoria
        fields = ['categoria','descripcion', 'estado']
        labels = {'descripcion':'Sub Categoria',
                    'estado':'Estado'}
        widget = {'descripcion': forms.TextInput}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control'
            })
        
        self.fields['categoria'].empty_label = "Seleccione Categoria"
    
    def clean(self):
        try:
            sc = SubCategoria.objects.get(
                descripcion=self.cleaned_data["descripcion"].upper()
            )

            if not self.instance.pk:
                print("Registro ya existe")
                raise forms.ValidationError("Registro Ya Existe")
            elif self.instance.pk!=sc.pk:
                print("Cambio no permitido")
                raise forms.ValidationError("Cambio No Permitido")
        except SubCategoria.DoesNotExist:
            pass
        return self.cleaned_data

class ProductoForm(forms.ModelForm):
    class Meta:
        model=Producto
        fields=['codigo','codigo_barra','descripcion','estado',\
            'precio','existencia','fecha_carga','cantidad', \
            'comentario', 'subCategoria']
        exclude=['um','fm','uc_id','fc',]
        widget = {'descripcion': forms.TextInput}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control'
            })
    
        self.fields['fecha_carga'].widget.attrs['readonly'] = True
       # self.fields['existencia'].widget.attrs['readonly'] = True
   

class BitacoraForm(forms.ModelForm):
    class Meta:
        model=Bitacora
        fields=['codigo','numero_documento','numero_viaje','fecha_recepcion',\
            'hora_recepcion','subCategoria','ubicacion','inicial', \
            'final', 'litros_recibidos','diferencia', 'tk','temperatura',\
            'api', 'descripcion']
        exclude=['um','fm','uc_id','fc',]
        widget = {'descripcion': forms.TextInput}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control'
            })
    
    

inv/views.py
from django.http.response import JsonResponse
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy

from django.contrib.auth.mixins import LoginRequiredMixin, \
    PermissionRequiredMixin

from .models import Categoria, SubCategoria, Producto, Bitacora
from .forms import CategoriaForm, SubCategoriaForm, ProductoForm, BitacoraForm

from bases.views import SinPrivilegios


class MixingFormInvalid:
        #duplicadp de datos
    def form_invalid(self, form):
        response = super().form_invalid(form)

        if self.request.is_ajax():
            return JsonResponse(form.errors, status=400)
        else:
            return response


class CategoriaView(SinPrivilegios, \
    generic.ListView):
    permission_required = "inv.view_categoria"
    model = Categoria
    template_name = "inv/categoria_list.html"
    context_object_name = "obj"


class CategoriaNew(LoginRequiredMixin,MixingFormInvalid, generic.CreateView):
    model=Categoria
    template_name="inv/categoria_form.html"
    context_object_name = "obj"
    form_class= CategoriaForm
    success_url=reverse_lazy("inv:categoria_list")
    login_url = 'bases:login'

    #sobre escribir el metodo para tener acceso a la informacion y tomar el usuario logeado (id)

    def form_valid(self, form):
        form.instance.uc = self.request.user
        return super().form_valid(form)


class CategoriaEdit(LoginRequiredMixin, MixingFormInvalid, generic.UpdateView):
    model=Categoria
    template_name="inv/categoria_form.html"
    context_object_name = "obj"
    form_class= CategoriaForm
    success_url=reverse_lazy("inv:categoria_list")
    login_url = 'bases:login'

    #sobre escribir el metodo para tener acceso a la informacion y tomar el usuario logeado (id)

    def form_valid(self, form):
        form.instance.um = self.request.user.id
        return super().form_valid(form)


class CategoriaDelete(LoginRequiredMixin, generic.DeleteView):
    model=Categoria
    template_name='inv/categoria_delete.html'
    context_object_name = "obj"
    success_url=reverse_lazy("inv:categoria_list")


class SubCategoriaView( SinPrivilegios, \
    generic.ListView):
    permission_required= "inv.view_subcategoria"
    model = SubCategoria
    template_name = "inv/sub_categoria_list.html"
    context_object_name = "obj"
  
  
class SubCategoriaNew(LoginRequiredMixin,MixingFormInvalid, generic.CreateView):
    model=SubCategoria
    template_name="inv/sub_categoria_form.html"
    context_object_name = "obj"
    form_class= SubCategoriaForm
    success_url=reverse_lazy("inv:subcategoria_list")
    login_url = 'bases:login'

    #sobre escribir el metodo para tener acceso a la informacion y tomar el usuario logeado (id)

    def form_valid(self, form):
        form.instance.uc = self.request.user
        return super().form_valid(form)

class SubCategoriaEdit(LoginRequiredMixin, MixingFormInvalid, generic.UpdateView):
    model=SubCategoria
    template_name="inv/sub_categoria_form.html"
    context_object_name = "obj"
    form_class= SubCategoriaForm
    success_url=reverse_lazy("inv:subcategoria_list")
    login_url = 'bases:login'

    #sobre escribir el metodo para tener acceso a la informacion y tomar el usuario logeado (id)

    def form_valid(self, form):
        form.instance.um = self.request.user.id
        return super().form_valid(form)

class SubCategoriaDelete(LoginRequiredMixin, generic.DeleteView):
    model=SubCategoria
    template_name='inv/subcategoria_delete.html'
    context_object_name = "obj"
    success_url=reverse_lazy("inv:subcategoria_list")

class ProductoView(LoginRequiredMixin, generic.ListView):
    model = Producto
    template_name = "inv/producto_list.html"
    context_object_name = "obj"
    login_url = 'bases:login'

class ProductoNew(LoginRequiredMixin, generic.CreateView):
    model=Producto
    template_name="inv/producto_form.html"
    context_object_name = "obj"
    form_class= ProductoForm
    success_url=reverse_lazy("inv:producto_list")
    login_url = 'bases:login'


    def form_valid(self, form):
        form.instance.uc = self.request.user
        return super().form_valid(form)

class ProductoEdit(LoginRequiredMixin, generic.UpdateView):
    model=Producto
    template_name="inv/producto_form.html"
    context_object_name = "obj"
    form_class= ProductoForm
    success_url=reverse_lazy("inv:producto_list")
    login_url = 'bases:login'


    def form_valid(self, form):
        form.instance.um = self.request.user.id
        return super().form_valid(form)

class ProductoDelete(LoginRequiredMixin, generic.DeleteView):
    model=Producto
    template_name='inv/producto_delete.html'
    context_object_name = "obj"
    success_url=reverse_lazy("inv:producto_list")

def producto_inactivar(request, id):
    prod = Producto.objects.filter(pk=id).first()
    contexto={}
    template_name="inv:catalogos_del.html"

    if not prod:
        return redirect("inv:producto_list")

    if request.method =='GET':
        contexto={'obj':prod}
    
    if request.method =='POST':
        prod.estado=False
        prod.save()
        return redirect("inv:producto_list")
    
    return render(request,template_name,contexto)

class BitacoraView(LoginRequiredMixin, generic.ListView):
    model = Bitacora
    template_name = "inv/bitacora_list.html"
    context_object_name = "obj"
    login_url = 'bases:login'

class BitacoraNew(LoginRequiredMixin, generic.CreateView):
    model=Bitacora
    template_name="inv/bitacora_form.html"
    context_object_name = "obj"
    form_class= BitacoraForm
    success_url=reverse_lazy("inv:bitacora_list")
    login_url = 'bases:login'

    #sobre escribir el metodo para tener acceso a la informacion y tomar el usuario logeado (id)

    def form_valid(self, form):
        form.instance.uc = self.request.user
        return super().form_valid(form)

class BitacoraEdit(LoginRequiredMixin, generic.UpdateView):
    model=Bitacora
    template_name="inv/bitacora_form.html"
    context_object_name = "obj"
    form_class= BitacoraForm
    success_url=reverse_lazy("inv:bitacora_list")
    login_url = 'bases:login'

    #sobre escribir el metodo para tener acceso a la informacion y tomar el usuario logeado (id)

    def form_valid(self, form):
        form.instance.um = self.request.user.id
        return super().form_valid(form)

class BitacoraDelete(LoginRequiredMixin, generic.DeleteView):
    model=Bitacora
    template_name='inv/bitacora_delete.html'
    context_object_name = "obj"
    success_url=reverse_lazy("inv:bitacora_list")

inv/templates/inv/bitacora_delete.html
{% block page_content %}
<!-- Earnings (Monthly) Card Example -->
<div class="modal-dialog">
    <div class="modal-content">
        <form method="POST" role="form" action="{% url 'inv:bitacora_delete'  obj.pk %}">
            {% csrf_token %}
            <!-- Pending Requests Card Example -->
                <div class="card border-left-danger shadow h-100 py-2">
                    <div class="card-body">                    
                        <div class="col-md-12">
                            <div class="modal-title text-primari mb-1">  <i class="fas fa-comments fa-2x text-gray-300"></i>   ¿Deseas Eliminar {{ obj.descripcion }} ?</div>
                          
                        </div>

                        <div class="modal-footer">
                            <button type="submit" class="btn btn-primary">Aceptar</button>
                            <a href="{% url 'inv:bitacora_list' %}" class="btn btn-danger"><span>Cancelar</span></a>
                        </div>
                    </div>
                </div>
        </form>
    </div>
</div>

{% endblock %}
{% block js_page %}
{% endblock %}

inv/templates/inv/bitacora_list.html
{% extends 'base/base.html' %}

{% block page_content %}


<div class="container container-xl">
    <div class="row">
        <div class="col-12">
                <!-- Dropdown Card Example -->
                <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold">Bitacora Recepción de Camiones</h6>
                    <div class="dropdown no-arrow">
                    <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                        <div class="dropdown-header">Acciones</div>
                        <a class="dropdown-item" href="#"  onclick="return mostrar_modal('{% url 'inv:bitacora_new' %}')" >Agregar</a>
                    </div>
                    </div>
                </div>
                <!-- Card Body -->
            
                <div class="card-body">
                    {% if not obj %}
                    <div class="alert alert-info">No hay Bitacora</div> 
                    {% else %} 
                    <table class="table table-striped table-hover">
                        <thead>
                            <th>codigo</th>
                            <th>numero doc</th>
                            <th>numero_viaje</th>
                            <th>fecha recepcion</th>
                            <th>hora</th>
                            <th>subCategoria</th>
                            <th>ubicacion</th>
                            <th>inicial</th>
                            <th>final</th>
                            <th>litros_recibidos</th>
                            <th>diferencia</th>
                            <th>tk</th>
                            <th>temperatura</th>
                            <th>api</th>
                            <th>descripcion</th>
                            <th class="all">Acciones</th>
                        </thead>
                        <tbody>
                            {% for item in obj %}
                                <tr>
                                    <td>{{ item.codigo }}</td>
                                    <td>{{ item.numero_documento }}</td>
                                    <td>{{ item.numero_viaje }}</td>
                                    <td>{{ item.fecha_recepcion|date:"d/m/Y" }}</td>
                                    <td>{{ item.hora_recepcion|date:"d/m/Y" }}</td>
                                    <td>{{ item.subCategoria }}</td>
                                    <td>{{ item.ubicacion }}</td>
                                    <td>{{ item.inicial }}</td>
                                    <td>{{ item.final }}</td>
                                    <td>{{ item.litros_recibidos }}</td>
                                    <td>{{ item.diferencia }}</td>
                                    <td>{{ item.tk }}</td>
                                    <td>{{ item.temperatura }}</td>
                                    <td>{{ item.api }}</td>
                                    <td>{{ item.descripcion }}</td>
                                    <td>
                                        <a href="#" onclick="return mostrar_modal('{% url 'inv:bitacora_edit' item.id  %}')" class="btn btn-primary btn-circle" role="button" data-toggle="tooltip" data-placement="top" title="Editar"><i class="far fa-edit"></i></a>
                                        <a href="#" class="btn btn-danger btn-circle"  onclick="return mostrar_modal('{% url 'inv:bitacora_delete' item.id  %}')"  role="button" data-toggle="tooltip" data-placement="top" title="Eliminar"><i class="far fa-trash-alt"></i></a>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    {% endif %}
                </div>
                </div>
        </div>
    </div>
  </div>


 
{% endblock %}

{% block js_page %}
<script>
    // Call the dataTables jQuery plugin
    $(document).ready(function() {
      $('.table').DataTable({
        "language": {
          "sProcessing": "Procesando...",
          "sLengthMenu": "Mostrar _MENU_ registros",
          "sZeroRecords": "No se encontraron resultados",
          "sEmptyTable": "Ningún dato disponible en esta tabla",
          "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
          "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
          "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
          "sInfoPostFix": "",
          "sSearch": "Buscar:",
          "sUrl": "",
          "sInfoThousands": ",",
          "sLoadingRecords": "Cargando...",
          "oPaginate": {
              "sFirst": "<span class='fa fa-angle-double-left'></span>",
              "sLast": "<span class='fa fa-angle-double-right'></span>",
              "sNext": "<span class='fa fa-angle-right'></span>",
              "sPrevious": "<span class='fa fa-angle-left'></span>"
          },
          "oAria": {
              "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
              "sSortDescending": ": Activar para ordenar la columna de manera descendente"
          }
        }
      });
    });
    </script>
{% endblock %}

inv/templates/inv/categoria_form.html
{% block page_content %}
<!-- Earnings (Monthly) Card Example -->
<div class="modal-dialog">
    <div class="modal-content">

        {% if obj %}
        <form method="POST" id="formCategoria" role="form" action="{% url 'inv:categoria_edit' obj.pk %}">
            <!-- Agregar token de seguridad a los formularios -->
        {% else %}
        <form method="POST" role="form" id="formCategoria" action="{% url 'inv:categoria_new' %}">
        {% endif %}
            {% csrf_token %}

                {% if obj %}
                       <!-- si viene un objeto se trata de una actualizacion -->
                    <div class="card border-left-warning shadow h-100 py-2">
                    {% else %}
                    <div class="card border-left-primary shadow h-100 py-2">
                    {% endif %}
                        <div class="card-body">
                        <div class="row no-gutters align-items-center">
                            <div class="col mr-2">
                                <div class="font-weight-bold text-primary mb-1">
                                    {% if obj%}
                                        Editar
                                    {% else %}
                                        Nueva 
                                    {% endif %}    
                                        Categoría                        
                                </div>
                                <div class="dropdown-divider"></div>
                                <div class="row">
                                    <div class="col-10">
                                        <div class="input-group">
                                            <input type="text" name="descripcion" maxlength="100" class="form-control" required id="id_descripcion" placeholder="Descripcion"
                                            value="{% if obj%} {{ obj.descripcion }} {% endif %}">
                                        </div>
                                    </div>
                                    <div class="col-2">
                                        <div class="input-group">
                                            <label for="id_estado">Estado</label>
                                            <input type="checkbox" name="estado" class="form-control" id="id_estado" {% if obj.estado %} checked {% endif %} >
                                        </div>
                                    </div>
                                </div>
                            
                                <div class="modal-footer">
                                    <button type="submit" class="btn btn-primary "><span>Guardar</span></button>
                                    <a href="{% url 'inv:categoria_list' %}" class="btn btn-danger"><span>Cancelar</span></a>
                                </div>
                            </div>
                        </div>
                        </div>
                    </div>
</form>
    </div>
</div>



{% endblock %}
{% block js_page %}
<script>
    $(function() {
    
        var url = $("#formCategoria").attr("action");
        var token = jQuery("[name=csrfmiddlewaretoken]").val();
        
        $("form").submit(function(e){
            e.preventDefault();
            // alert(token);
            var formData = $("form").serializeArray();
            // console.log(formData);
            $.ajax({
                url:url,
                method:"POST",
                headers: {'X-CSRFToken': token },
                data: formData
            })
            .done(function(r,textStatus,xhr){
                if(xhr.status=200){
                    location.reload(true);
                }
                else{
                    mensaje(textStatus);
                }
            }).fail(function (error) {
                    mensaje(error.responseText);
            });
        });
    });
</script>
{% endblock %}

inv/templates/inv/categoria_list.html
{% extends 'base/base.html' %}

{% block page_content %}


<div class="container ">
    <div class="row">
      <div class="col-12">
    <!-- Dropdown Card Example -->
    <div class="card shadow mb-4">
        <!-- Card Header - Dropdown -->
        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
            <h6 class="m-0 font-weight-bold">Listar Categorías</h6>
            <div class="dropdown no-arrow">
            <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                <div class="dropdown-header">Acciones</div>
                <a class="dropdown-item" href="#"  onclick="return mostrar_modal('{% url 'inv:categoria_new' %}')" ><i class="fas fa-plus"></i> Agregar Categoría</a>
            </div>
            </div>
        </div>
        <!-- Card Body -->
    
        <div class="card-body">
            {% if not obj %}
            <div class="alert alert-info">No hay categoria</div> 
            {% else %}
            <table class="table table-striped table-hover">
                <thead>
                    <th>Id</th>
                    <th>Descripción</th>
                    <th>Estado</th>
                    <th>Fecha Creacion</th>
                    <th>Fecha Modificacion</th>
                    <th class="all">Acciones</th>
                </thead>
                <tbody>
                    {% for item in obj %}
                        <tr>
                            <td>{{ item.id }}</td>
                            <td>{{ item.descripcion }}</td>
                            <td>{{ item.estado|yesno:"Activo, Inactivo" }}</td>
                            <td>{{ item.fc|date:"d/m/Y H:i:s" }}</td>
                            <td>{{ item.fm|date:"d/m/Y H:i:s" }}</td>
                            <td>
                                <a href="#" class="btn btn-primary btn-circle" onclick="return mostrar_modal('{% url 'inv:categoria_edit' item.id  %}')" role="button" data-toggle="tooltip" data-placement="top" title="Editar"><i class="far fa-edit"></i></a>
                                <a href="#" class="btn btn-danger btn-circle"  onclick="return mostrar_modal('{% url 'inv:categoria_delete' item.id  %}')"  role="button" data-toggle="tooltip" data-placement="top" title="Eliminar"><i class="far fa-trash-alt"></i></a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% endif %}
        </div>
        </div>
      </div>
    </div>
  </div>


 
{% endblock %}

{% block js_page %}
<script>
    // Call the dataTables jQuery plugin
    $(document).ready(function() {
      
      $('.table').DataTable({
        "language": {
          "sProcessing": "Procesando...",
          "sLengthMenu": "Mostrar _MENU_ registros",
          "sZeroRecords": "No se encontraron resultados",
          "sEmptyTable": "Ningún dato disponible en esta tabla",
          "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
          "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
          "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
          "sInfoPostFix": "",
          "sSearch": "Buscar:",
          "sUrl": "",
          "sInfoThousands": ",",
          "sLoadingRecords": "Cargando...",
          "oPaginate": {
              "sFirst": "<span class='fa fa-angle-double-left'></span>",
              "sLast": "<span class='fa fa-angle-double-right'></span>",
              "sNext": "<span class='fa fa-angle-right'></span>",
              "sPrevious": "<span class='fa fa-angle-left'></span>"
          },
          "oAria": {
              "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
              "sSortDescending": ": Activar para ordenar la columna de manera descendente"
          }
        }
      });
    });
    </script>
{% endblock %}