app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    
    path('',include(('bases.urls', 'bases'), namespace='bases')),
    path('inv/',include(('inv.urls','inv'), namespace='inv')),
    path('vnt/',include(('vnt.urls','vnt'), namespace='vnt')),
    path('fac/',include(('fac.urls','fac'), namespace='fac')),
    path('apiRest/', include(('apiRest.urls', 'apiRest'), namespace='apiRest')),

    path('admin/', admin.site.urls),
]

vnt/urls.py
from django.urls import path, include

from .views import ProveedorView,ProveedorNew,ProveedorEdit, \
    proveedorInactivar, VentasView, ventas

from .reportes import reporte_ventas, imprimir_venta

urlpatterns = [
    path('proveedores/', ProveedorView.as_view(), name='proveedores_list'),
    path('proveedores/new', ProveedorNew.as_view(), name='proveedores_new'),
    path('proveedores/edit/<int:pk>', ProveedorEdit.as_view(), name='proveedores_edit'),
    path('proveedores/inactiva/<int:id>', proveedorInactivar, name='proveedor_inactivar'),

    path('ventas/', VentasView.as_view(), name='ventas_list'),
    path('ventas/new', ventas, name='ventas_new'),
    path('ventas/edit/<int:venta_id>',ventas, name="ventas_edit"),


 
]

vnt/models.py
from django.db import models
#signals
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver

from bases.models import ClaseModelo
from inv.models import Producto

class Proveedor(ClaseModelo):
    descripcion=models.CharField(
        max_length=100,
        unique=True
    )
    direccion=models.CharField(
        max_length=250,
        null=True, blank=True
    )
    contacto=models.CharField(
        max_length=100,
    )
    telefono=models.CharField(
        max_length=10,
        null=True, blank=True
    )
    email=models.CharField(
        max_length=250,
    )

    def __str__(self):
        return '{}'.format(self.descripcion)

    def save(self):
        self.descripcion = self.descripcion.upper()
        super(Proveedor, self).save()

    class Meta:
        verbose_name_plural= "Proveedores"

class VentasEnc(ClaseModelo):
    fecha_venta = models.DateField(null=True, blank=True)
    observacion = models.TextField(blank=True, null=True)
    no_factura = models.CharField(max_length=100)
    fecha_factura = models.DateField(null=True, blank=True)
    sub_total = models.FloatField(default=0)
    descuento = models.FloatField(default=0)
    total = models.FloatField(default=0)

    proveedor = models.ForeignKey(Proveedor, on_delete=models.CASCADE)

    def __str__(self):
        return '{}'.format(self.observacion)
    def save(self):
        self.observacion = self.observacion.upper()
        self.total = self.sub_total - self.descuento
        super(VentasEnc, self).save()
    
    class Meta:
        verbose_name_plural= "Encabezados Ventas"
        verbose_name= "Encabezado Venta"


class VentasDet(ClaseModelo):
    venta = models.ForeignKey(VentasEnc, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    cantidad=models.BigIntegerField(default=0)
    precio_prv=models.FloatField(default=0)
    sub_total=models.FloatField(default=0)
    descuento=models.FloatField(default=0)
    total=models.FloatField(default=0)
    costo=models.FloatField(default=0)

    def __str__(self):
        return '{}'.format(self.producto)

    def save(self):
        self.sub_total = float(float(int(self.cantidad)) * float(self.precio_prv))
        self.total = self.sub_total - float(self.descuento)
        super(VentasDet, self).save()

    class Meta:
        verbose_name_plural= "Detalles Ventas"
        verbose_name= "Detalle Venta"


 

vnt/forms.py
from django import forms

from .models import Proveedor, VentasEnc

class ProveedorForm(forms.ModelForm):
    email = forms.EmailField(max_length=250)
    class Meta:
        model = Proveedor
        exclude = ['um','fm','uc_id','fc']
        widget = {'descripcion': forms.TextInput()}
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control'
            })
    
    def clean(self):
        try:
            sc = Proveedor.objects.get(
                descripcion=self.cleaned_data["descripcion"].upper()
            )

            if not self.instance.pk:
                print("Registro ya existe")
                raise forms.ValidationError("Registro Ya Existe")
            elif self.instance.pk!=sc.pk:
                print("Cambio no permitido")
                raise forms.ValidationError("Cambio No Permitido")
        except Proveedor.DoesNotExist:
            pass
        return self.cleaned_data



class VentasEncForm(forms.ModelForm):
    fecha_venta = forms.DateInput()
    fecha_factura = forms.DateInput()

    class Meta:
        model = VentasEnc
        fields= ['proveedor','fecha_venta','observacion','no_factura',
                'fecha_factura',
                'sub_total','descuento','total']
        widgets = {
            'fecha_factura': forms.DateInput(format=('%Y-%m-%d'), 
                                             attrs={'class':'myDateClass', 
                                            'placeholder':'Select a date'})
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control'
            })
        ##self.fields['fecha_venta'].widget.attrs['readonly'] = True
        #self.fields['fecha_factura'].widget.attrs['readonly'] = True
        self.fields['sub_total'].widget.attrs['readonly'] = True
        self.fields['descuento'].widget.attrs['readonly'] = True
        self.fields['total'].widget.attrs['readonly'] = True

vnt/views.py
from django.http.response import JsonResponse
from django.shortcuts import render, redirect
from django.views import generic
from django.urls import reverse_lazy
import datetime
from django.http import HttpResponse

from django.contrib.auth.mixins import LoginRequiredMixin

from django.contrib.auth.decorators import login_required, permission_required
from django.http import HttpResponse
import json
from django.db.models import Sum

from .models import Proveedor, VentasEnc, VentasDet
from vnt.forms import ProveedorForm, VentasEncForm
from inv.models import Producto 

class MixingFormInvalid:
        #duplicadp de datos
    def form_invalid(self, form):
        response = super().form_invalid(form)

        if self.request.is_ajax():
            return JsonResponse(form.errors, status=400)
        else:
            return response

class ProveedorView(LoginRequiredMixin, generic.ListView):
    model = Proveedor
    template_name = "vnt/proveedor_list.html"
    context_object_name = "obj"

    login_url = 'bases:login'


class ProveedorNew(LoginRequiredMixin,MixingFormInvalid, generic.CreateView):
    model = Proveedor
    template_name = "vnt/proveedor_form.html"
    context_object_name = "obj"
    form_class = ProveedorForm
    success_url=reverse_lazy("vnt:proveedores_list")
    login_url = 'bases:login'

    def form_valid(self, form):
        form.instance.uc = self.request.user
        return super().form_valid(form)



class ProveedorEdit(LoginRequiredMixin, MixingFormInvalid, generic.UpdateView):
    model=Proveedor
    template_name="vnt/proveedor_form.html"
    context_object_name = "obj"
    form_class= ProveedorForm
    success_url=reverse_lazy("vnt:proveedores_list")
    login_url = 'bases:login'

    def form_valid(self, form):
        form.instance.um = self.request.user.id
        return super().form_valid(form)

def proveedorInactivar(request,id):
    template_name="vnt/inactivar_proveedor.html"
    contexto= {}
    proveedor = Proveedor.objects.filter(pk=id).first()

    if not proveedor:
        return HttpResponse('Proveedor no Existe' + str(id))
    
    if request.method=='GET':
        contexto = {'obj':proveedor}
    
    if request.method=='POST':
        proveedor.estado = False
        proveedor.save()
        contexto = {'obj':'OK'}
        return HttpResponse('Proveedor Inactivado')


    return render(request,template_name,contexto)

class VentasView(LoginRequiredMixin, generic.ListView):
    model = VentasEnc
    template_name = "vnt/ventas_list.html"
    context_object_name = "obj"
    form_class= ProveedorForm
    success_url=reverse_lazy("vnt:ventas_list")
    login_url = 'bases:login'


@login_required(login_url="/login/")
@permission_required("vnt.view_ventasenc'",login_url='bases:sin_privilegios')
def ventas(request, venta_id=None):
    template_name = 'vnt/ventas.html'
    producto = Producto.objects.filter(estado = True)
    form_ventas = {}
    contexto = {}

    if request.method=='GET':
        form_ventas= VentasEncForm()
        encabezado = VentasEnc.objects.filter(pk=venta_id).first()

        if encabezado:
            detalle = VentasDet.objects.filter(venta= encabezado)
            fecha_venta = datetime.date.isoformat(encabezado.fecha_venta)
            fecha_factura = datetime.date.isoformat(encabezado.fecha_factura)
            e = {
                'fecha_venta': fecha_venta,
                'proveedor': encabezado.proveedor,
                'observacion': encabezado.observacion,
                'no_factura' : encabezado.no_factura,
                'fecha_factura' : encabezado.fecha_factura,
                'sub_total' : encabezado.sub_total,
                'descuento': encabezado.descuento,
                'total' : encabezado.total
            }

            form_ventas = VentasEncForm(e)
        else:
            detalle =  None
        contexto={'productos': producto, 'encabezado': encabezado, 'detalle': detalle, 'form_encabezado': form_ventas}


        #capturar todo el formulario

    if request.method== 'POST':
        #obtener con request.POST.get
        fecha_venta = request.POST.get("fecha_venta")
        observacion = request.POST.get("observacion")
        no_factura = request.POST.get("no_factura")
        fecha_factura = request.POST.get("fecha_factura")
        proveedor = request.POST.get("proveedor")
        #inicializar variables
        sub_total = 0
        descuento = 0
        total = 0

        #consultar por encabezado si existe

        if not venta_id:
            #guardar proveedor
            proveedor=Proveedor.objects.get(pk=proveedor)
            #inicializar

            encabezado = VentasEnc(
                fecha_venta=fecha_venta,
                observacion=observacion,
                no_factura=no_factura,
                fecha_factura=fecha_factura,
                proveedor=proveedor,
                uc = request.user
            )

            if encabezado:
                encabezado.save()
                venta_id = encabezado.id
        else:
            encabezado = VentasEnc.objects.filter(pk=venta_id).first()
            if encabezado:
                #actualizar 
                encabezado.fecha_venta = fecha_venta
                encabezado.observacion = observacion
                encabezado.no_factura = no_factura
                encabezado.fecha_factura = fecha_factura
                #usuario modifica
                encabezado.um = request.user.id
                encabezado.save()
        #si venta id no tiene nada
        if not venta_id:
            return redirect("vnt:ventas_list")

        #capturar datos del producto que se han enviado para el detalle

        producto = request.POST.get("id_id_producto")
        cantidad = request.POST.get("id_cantidad_detalle")
        precio = request.POST.get("id_precio_detalle")
        sub_total_detalle = request.POST.get("id_sub_total_detalle")
        descuento_detalle  = request.POST.get("id_descuento_detalle")
        total_detalle  = request.POST.get("id_total_detalle")

        prod = Producto.objects.get(pk=producto)

        detalle = VentasDet(
            venta = encabezado,
            producto = prod,
            cantidad = cantidad,
            precio_prv = precio,
            descuento = descuento_detalle,
            costo = 0,
            uc = request.user
        )

        if detalle:
            detalle.save()

            sub_total=VentasDet.objects.filter(venta=venta_id).aggregate(Sum('sub_total'))
            descuento = VentasDet.objects.filter(venta = venta_id ).aggregate(Sum('descuento'))

            encabezado.sub_total = sub_total["sub_total__sum"]
            encabezado.descuento = descuento["descuento__sum"]
            encabezado.save()
        
        return redirect("vnt:ventas_edit", venta_id = venta_id)

    



        

    return render(request, template_name, contexto)


    

vnt/templates/vnt/inactivar_proveedor.html
<!-- Earnings (Monthly) Card Example -->
<div class="modal-dialog">
    <div class="modal-content">
        <form method="POST" role="form">
            {% csrf_token %}
            <!-- Pending Requests Card Example -->
                <div class="card border-left-danger shadow h-100 py-2">
                    <div class="card-body">                    
                        <div class="col-md-12">
                            <div class="modal-title text-primari mb-1">  <i class="fas fa-comments fa-2x text-gray-300"></i>   ¿Deseas Inactivar {{ obj.descripcion }} ?</div>
                          
                        </div>

                        <div class="modal-footer">
                            <button type="button" id="btnInactivar" class="btn btn-primary">Aceptar</button>
                            <a href="{% url 'vnt:proveedores_list' %}" class="btn btn-danger"><span>Cancelar</span></a>
                        </div>
                    </div>
                </div>
        </form>
    </div>
</div>
<script>
    $(document).ready(function(){
    
      var token = $('input[name=csrfmiddlewaretoken]').val();
      $.ajaxSetup({
            beforeSend: function(xhr, settings) {
                if (!(/^http:.*/.test(settings.url) || /^https:.*/.test(settings.url))) {
                    xhr.setRequestHeader("X-CSRFToken", token);
                }
            }
        });
    
      $("#btnInactivar").click(function(e){
          e.preventDefault();
          //alert("Probando");
    
          var id = {{ obj.id }};
          var template="{% url 'vnt:proveedor_inactivar' obj.id %}";
          //template += id;
          var data = {"id":id};
          data = JSON.stringify(data);
    
          $.ajax({
            type: "POST",
            url: template,
            data: data,
            beforeSend: function(xhr,settings){
              $.ajaxSettings.beforeSend(xhr,settings);
            },
            success: function(response){
              console.log(response);
              cerrar_modal();
              //alert(response);
              var tipo=(response.startsWith('Proveedor no existe') ? 'red':'green' );
              //mensaje(response,tipo);
              location.reload();
            },
            error: function(jqXHR, textStatus, errorThrow){
              console.log(textStatus, errorThrow);
              //mensaje(errorThrow,'red');
              cerrar_modal();
            }
          });
      });
    
    });
    </script>

vnt/templates/vnt/proveedor_form.html
{% block page_content %}
<!-- Earnings (Monthly) Card Example -->

<div class="modal-dialog modal-xl">
    <div class="modal-content">
        {% if obj %}
        <form method="POST" id="formProveedor" role="form" class="form-inline" action="{% url 'vnt:proveedores_edit' obj.pk %}">
            <!-- Agregar token de seguridad a los formularios -->
        {% else %}
        <form method="POST" id="formProveedor" role="form" class="form-inline" action="{% url 'vnt:proveedores_new' %}">
        {% endif %}
            {% csrf_token %}
                {% if obj %}
                <!-- si viene un objeto se trata de una actualizacion -->
                <div class="card border-left-warning shadow h-100 py-2">
                {% else %}
                <div class="card border-left-primary shadow h-100 py-2">
                {% endif %}
                    <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="font-weight-bold text-primary mb-1">
                                {% if obj%}
                                    Editar
                                {% else %}
                                    Agregar
                                {% endif %}    
                                    Proveedor                       
                            </div>
                            <div class="dropdown-divider"></div>
                            <div class="row">
                                {{ form.as_p }}
                            </div>
                            <div class="dropdown-divider"></div>
                            <di class="row">
                                <div class="col">
                                    <button type="submit" class="btn btn-primary"><span>Guardar</span></button>
                                    <a href="{% url 'vnt:proveedores_list' %}" class="btn btn-danger"><span>Cancelar</span></a>
                                </div>
                            </di>
                        </div>
                    </div>
                    </div>
                </div>

        </form>
    </div>
</div>

{% endblock %}
{% block js_page %}
<script>
    $(function() {
    
        var url = $("#formProveedor").attr("action");
        var token = jQuery("[name=csrfmiddlewaretoken]").val();
        
        $("form").submit(function(e){
            e.preventDefault();
            // alert(token);
            var formData = $("form").serializeArray();
            // console.log(formData);
            $.ajax({
                url:url,
                method:"POST",
                headers: {'X-CSRFToken': token },
                data: formData
            })
            .done(function(r,textStatus,xhr){
                if(xhr.status=200){
                    location.reload(true);
                }
                else{
                    mensaje(textStatus);
                }
            }).fail(function (error) {
                    mensaje(error.responseText);
            });
        });
    });
</script>
{% endblock %}

vnt/templates/vnt/proveedor_list.html
{% extends 'base/base.html' %}

{% block page_content %}


<div class="container container-xl">
    <div class="row">
      <div class="col-12">
    <!-- Dropdown Card Example -->
    <div class="card shadow mb-4">
        <!-- Card Header - Dropdown -->
        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
            <h6 class="m-0 font-weight-bold">Lista de Proveedores</h6>
            <div class="dropdown no-arrow">
            <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                <div class="dropdown-header">Acciones</div>
                <a class="dropdown-item" href="#"  onclick="return mostrar_modal('{% url 'vnt:proveedores_new' %}')" ><i class="fas fa-plus"></i> Agregar</a>
            </div>
            </div>
        </div>
        <!-- Card Body -->
    
        <div class="card-body">
            {% if not obj %}
            <div class="alert alert-info">No hay Proveedores</div> 
            {% else %} 
            <table class="table table-striped table-hover">
                <thead>
                  
                    <th>Id</th>
                    <th>Descripcion</th>
                    <th>Direccion</th>
                    <th>Contacto</th>
                    <th>Teléfono</th>
                    <th>Email</th>
                    <th>Estado</th>
                    <th class="all">Acciones</th>
                </thead>
                <tbody>
                    {% for item in obj %}
                        <tr>
                            
                            <td>{{ item.id }}</td>
                            <td>{{ item.descripcion }}</td>
                            <td>{{ item.direccion }}</td>
                            <td>{{ item.contacto}}</td>
                            <td>{{ item.telefono }}</td>
                            <td>{{ item.email }}</td>
                            <td>{{ item.estado|yesno:"Activo, Inactivo"}}</td>
                            <td>
                                <a href="#" onclick="return mostrar_modal('{% url 'vnt:proveedores_edit' item.id  %}')" class="btn btn-primary btn-circle" role="button" data-toggle="tooltip" data-placement="top" title="Editar"><i class="far fa-edit"></i></a>
                                <a href="#" onclick="return mostrar_modal('{% url 'vnt:proveedor_inactivar' item.id  %}')" class="btn btn-warning btn-circle" role="button" data-toggle="tooltip" data-placement="top" title="Editar"><i class="far fa-thumbs-down"></i></a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% endif %}
        </div>
        </div>
      </div>
    </div>
  </div>


 
{% endblock %}

{% block js_page %}
<script>
    // Call the dataTables jQuery plugin
    $(document).ready(function() {
      $('.table').DataTable({
        "language": {
          "sProcessing": "Procesando...",
          "sLengthMenu": "Mostrar _MENU_ registros",
          "sZeroRecords": "No se encontraron resultados",
          "sEmptyTable": "Ningún dato disponible en esta tabla",
          "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
          "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
          "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
          "sInfoPostFix": "",
          "sSearch": "Buscar:",
          "sUrl": "",
          "sInfoThousands": ",",
          "sLoadingRecords": "Cargando...",
          "oPaginate": {
              "sFirst": "<span class='fa fa-angle-double-left'></span>",
              "sLast": "<span class='fa fa-angle-double-right'></span>",
              "sNext": "<span class='fa fa-angle-right'></span>",
              "sPrevious": "<span class='fa fa-angle-left'></span>"
          },
          "oAria": {
              "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
              "sSortDescending": ": Activar para ordenar la columna de manera descendente"
          }
        }
      });
    });
    </script>
{% endblock %}

vnt/templates/vnt/venta_print.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Listado de Venta</title>

    <style type="text/css">
    @page {
        size: letter;
        margin: 1cm;
    }

    .table td .numero{
        text-align: center;
    }
    </style>
</head>
<body>
    <div class="container">
        <div class="card">
            <div class="card-header">
                <h4>Sistema de Venta</h4>
            </div>

            <div class="list-group">
                <p>No. Venta: {{ encabezado.id}} </p>
                <table class="">
                    <tbody>
                        <tr>
                            <td>Proveedor:</td>
                            <td>{{ encabezado.proveedor}}</td>
                            <td>Fecha Ventas:</td>
                            <td>{{ encabezado.fecha_venta|date:"d/m/Y"}}</td>
                        </tr>
                        <tr>
                            <td>No. Factura</td>
                            <td>{{encabezado.no_factura}}</td>
                            <td>Fecha Factura:</td>
                            <td>{{ encabezado.fecha_factura|date:"d/m/Y"}}</td>
                        </tr>
                        <tr>
                            <td>Observación:</td>
                            <td colspan="3">{{encabezado.Observación}}</td>
                        </tr>
                    </tbody>
                </table>
                <hr>
            </div>


            <table class="table">
                <thead>
                    <tr>
                        <th>Sub total</th>
                        <th>Producto</th>
                        <th>Cantidad</th>
                        <th>Sub total</th>
                        <th>Descuento</th>
                        <th>Total</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in detalle %}
                    <tr>
                        <td><span class="small">{{ item.producto }}</span></td>
                        <td class="numero">{{ item.cantidad }}</td>
                        <td class="numero">{{ item.precio_prv }}</td>
                        <td class="numero">{{ item.sub_total }}</td>
                        <td class="numero">{{ item.descuento }}</td>
                        <td class="numero">{{ item.total }}</td>
                    </tr>
                    {% endfor %}
                    <tr>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                          </tr>
                          <tr>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td><h4>Sub Total</h4></td>
                            <td class="numero"><h4>{{ encabezado.sub_total}}</h4></td>
                          </tr>
                          <tr>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td><h4>Descuento</h4></td>
                            <td class="numero"><h4>{{ encabezado.descuento}}</h4></td>
                          </tr>
                          <tr>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td></td>
                            <td><h4>Total</h4></td>
                            <td class="numero"><h4>{{ encabezado.total}}</h4></td>
                          </tr>

                </tbody>
            </table>
        </div>
    </div>
</body>
</html>

vnt/templates/vnt/ventas_list.html
{% extends 'base/base.html' %}

{% block page_content %}


<div class="container container-xl">
    <div class="row">
      <div class="col-12">
    <!-- Dropdown Card Example -->
    <div class="card shadow mb-4">
        <!-- Card Header - Dropdown -->
        <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
            <h6 class="m-0 font-weight-bold">Lista de Ventas</h6>
            <div class="dropdown no-arrow">
            <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                <div class="dropdown-header">Acciones</div>
                <a class="dropdown-item" href="{% url 'vnt:ventas_new' %}" ><i class="fas fa-plus"></i> Agregar</a>
                <a class="dropdown-item" href="{% url 'vnt:ventas_print_all' %}" ><i class="fas fa-print"></i> Listado</a>
            </div>
            </div>
        </div>
        <!-- Card Body -->
    
        <div class="card-body">
            {% if not obj %}
            <div class="alert alert-info">No hay Ventas</div> 
            {% else %} 
            <table class="table table-striped table-hover">
                <thead>
                  
                    <th>Id</th>
                    <th>Fecha </th>
                    <th>Observación</th>
                    <th>N° Factura</th>
                    <th>Fecha Factura</th>
                    <th>Sub Total</th>
                    <th>Descueto</th>
                    <th>Total</th>
                    <th>Estado</th>
                   <th class="all">Acciones</th>
                </thead>
                <tbody>
                    {% for item in obj %}
                        <tr>
                            
                            <td>{{ item.id }}</td>
                            <td>{{ item.fecha_venta }}</td>
                            <td>{{ item.observacion }}</td>
                            <td>{{ item.no_factura}}</td>
                            <td>{{ item.fecha_factura }}</td>
                            <td>{{ item.sub_total }}</td>
                            <td>{{ item.descuento }}</td>
                            <td>{{ item.total }}</td>
                            <td>{{ item.estado|yesno:"Activo, Inactivo"}}</td>
                          <td>
                                <a href="{% url 'vnt:ventas_edit' item.id %}" class="btn btn-primary btn-circle" role="button" data-toggle="tooltip" data-placement="top" title="Editar"><i class="far fa-edit"></i></a>
                                <a  href="{% url 'vnt:ventas_print' item.id %}"  class="btn btn-primary btn-circle" role="button" data-toggle="tooltip" data-placement="top" title="Editar"><i class="fas fa-print"></i></a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% endif %}
        </div>
        </div>
      </div>
    </div>
  </div>


 
{% endblock %}

{% block js_page %}
<script>
    // Call the dataTables jQuery plugin
    $(document).ready(function() {
      $('.table').DataTable({
        "language": {
          "sProcessing": "Procesando...",
          "sLengthMenu": "Mostrar _MENU_ registros",
          "sZeroRecords": "No se encontraron resultados",
          "sEmptyTable": "Ningún dato disponible en esta tabla",
          "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
          "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
          "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
          "sInfoPostFix": "",
          "sSearch": "Buscar:",
          "sUrl": "",
          "sInfoThousands": ",",
          "sLoadingRecords": "Cargando...",
          "oPaginate": {
              "sFirst": "<span class='fa fa-angle-double-left'></span>",
              "sLast": "<span class='fa fa-angle-double-right'></span>",
              "sNext": "<span class='fa fa-angle-right'></span>",
              "sPrevious": "<span class='fa fa-angle-left'></span>"
          },
          "oAria": {
              "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
              "sSortDescending": ": Activar para ordenar la columna de manera descendente"
          }
        }
      });
    });
    </script>
{% endblock %}